const GITHUB_API = 'https://api.github.com';

function getHeaders(token) {
  return {
    'Authorization': `Bearer ${token}`,
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
    'User-Agent': 'iNSIGHTS-Layer2-Bot'
  };
}

async function createRepository(token, { name, description, isPrivate = true }) {
  const response = await fetch(`${GITHUB_API}/user/repos`, {
    method: 'POST', headers: getHeaders(token),
    body: JSON.stringify({ name, description, private: isPrivate, auto_init: false, has_issues: true, has_wiki: false })
  });
  if (!response.ok) { const err = await response.json(); throw new Error(`Failed to create repo: ${err.message}`); }
  return response.json();
}

async function getAuthenticatedUser(token) {
  const response = await fetch(`${GITHUB_API}/user`, { headers: getHeaders(token) });
  if (!response.ok) throw new Error('Failed to get authenticated user');
  return response.json();
}

async function createOrUpdateFile(token, owner, repo, path, content, message) {
  const encodedContent = Buffer.from(content, 'utf-8').toString('base64');
  let sha = null;
  try {
    const check = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/${path}`, { headers: getHeaders(token) });
    if (check.ok) { const existing = await check.json(); sha = existing.sha; }
  } catch (_) {}
  const body = { message, content: encodedContent };
  if (sha) body.sha = sha;
  const response = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/${path}`, { method: 'PUT', headers: getHeaders(token), body: JSON.stringify(body) });
  if (!response.ok) { const err = await response.json(); throw new Error(`Failed to create ${path}: ${err.message}`); }
  return response.json();
}

async function createMilestone(token, owner, repo, { title, description, dueDate }) {
  const body = { title, description };
  if (dueDate) body.due_on = dueDate;
  const response = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/milestones`, { method: 'POST', headers: getHeaders(token), body: JSON.stringify(body) });
  if (!response.ok) return null;
  return response.json();
}

async function createIssue(token, owner, repo, { title, body, labels, milestoneNumber }) {
  const issueBody = { title, body: body || title, labels: labels || [] };
  if (milestoneNumber) issueBody.milestone = milestoneNumber;
  const response = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/issues`, { method: 'POST', headers: getHeaders(token), body: JSON.stringify(issueBody) });
  if (!response.ok) return null;
  return response.json();
}

async function createLabel(token, owner, repo, { name, color, description }) {
  const response = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/labels`, { method: 'POST', headers: getHeaders(token), body: JSON.stringify({ name, color, description: description || '' }) });
  if (!response.ok) return null;
  return response.json();
}

export async function provisionProject(token, blueprint, options = {}) {
  const { repoName, isPrivate = true, includeReadme = true, includeIssues = true, includeEnvTemplate = true, includeMilestones = true } = options;
  const results = { repository: null, readme: null, envTemplate: null, milestones: [], issues: [], errors: [] };

  const user = await getAuthenticatedUser(token);
  const owner = user.login;
  const repo = await createRepository(token, { name: repoName, description: `${blueprint.tagline || blueprint.title} | Generated by iNSIGHTS Layer 2`, isPrivate });
  results.repository = { url: repo.html_url, fullName: repo.full_name };

  const labelDefs = [
    { name: 'P0', color: 'B60205', description: 'Critical priority' },
    { name: 'P1', color: 'E4E669', description: 'High priority' },
    { name: 'P2', color: '0075CA', description: 'Medium priority' },
    { name: 'setup', color: 'BFDADC', description: 'Project setup' },
    { name: 'feature', color: 'A2EEEF', description: 'New feature' },
    { name: 'ai/ml', color: 'D93F0B', description: 'AI/ML related' },
    { name: 'backend', color: 'E4E669', description: 'Backend work' },
    { name: 'frontend', color: '0052CC', description: 'Frontend work' }
  ];
  await Promise.allSettled(labelDefs.map(l => createLabel(token, owner, repo.name, l)));

  if (includeReadme) {
    const { buildReadmeContent } = await import('./prompt-builder.js');
    const content = buildReadmeContent(blueprint, repoName);
    try { await createOrUpdateFile(token, owner, repo.name, 'README.md', content, '🚀 Initial commit: AI-generated README'); results.readme = { created: true }; }
    catch (err) { results.errors.push(`README: ${err.message}`); }
  }

  if (includeMilestones && blueprint.sprints) {
    const milestoneMap = {};
    const today = new Date();
    for (let i = 0; i < blueprint.sprints.length; i++) {
      const sprint = blueprint.sprints[i];
      const dueDate = new Date(today); dueDate.setDate(today.getDate() + (i+1)*7);
      const milestone = await createMilestone(token, owner, repo.name, { title: `${sprint.week}: ${sprint.title}`, description: sprint.desc, dueDate: dueDate.toISOString() });
      if (milestone) { milestoneMap[i+1] = milestone.number; results.milestones.push({ number: milestone.number, title: milestone.title }); }
    }

    if (includeIssues && blueprint.githubIssues?.length > 0) {
      for (const issue of blueprint.githubIssues) {
        const created = await createIssue(token, owner, repo.name, { title: issue.title, body: issue.body, labels: issue.labels || ['feature'], milestoneNumber: milestoneMap[issue.week] || null });
        if (created) results.issues.push({ number: created.number, title: created.title, url: created.html_url });
        await new Promise(r => setTimeout(r, 100));
      }
    }
  }

  return results;
}
