'use strict';

/**
 * Build the structured prompt for blueprint generation
 * Uses few-shot examples to guide JSON output format
 */
function buildBlueprintPrompt(query, ragContext) {
  const systemPrompt = `You are iNSIGHTS Layer 2 — an elite AI innovation copilot for college students.
Your role: Transform vague project ideas into comprehensive, executable blueprints.

You MUST respond with a single valid JSON object. No markdown, no preamble, no explanation.
The JSON must exactly match this schema:

{
  "title": "Short catchy project title (max 8 words)",
  "tagline": "One line tagline (max 10 words)",
  "problemStatement": "2-3 sentence description of the problem being solved",
  "techStack": {
    "frontend": ["Technology1", "Technology2"],
    "backend": ["Technology1", "Technology2"],
    "database": ["Technology1"],
    "aiMl": ["Technology1", "Technology2"],
    "devops": ["Technology1", "Technology2"]
  },
  "architectureMermaid": "graph TD\n  A[\"Component1\"] --> B[\"Component2\"]\n  ...",
  "stats": [
    {"val": "number or stat", "label": "description"}
  ],
  "warning": "Key problem with current manual approaches (1-2 sentences)",
  "arch": [
    {"icon": "emoji", "title": "Layer Name", "stack": "Tech, Stack", "hl": false}
  ],
  "deepSearchResults": [
    {
      "type": "paper | github | patent",
      "title": "Title of paper or repo",
      "source": "IEEE | arXiv | GitHub",
      "desc": "1-2 sentence relevance description",
      "url": "https://actual-url-if-available"
    }
  ],
  "mentorChat": [
    {"from": "bot", "text": "Opening message from AI mentor"},
    {"from": "user", "text": "Example user question"},
    {"from": "bot", "text": "Expert answer from mentor"}
  ],
  "webIntel": [
    {"status": "safe | warn | critical", "lib": "library@version", "detail": "status details", "badge": "UP TO DATE | MIGRATE | CVE FOUND"}
  ],
  "sprints": [
    {"week": "W1", "title": "Sprint Theme", "desc": "What gets built", "done": false}
  ],
  "githubIssues": [
    {
      "title": "Issue title",
      "body": "Issue description with acceptance criteria",
      "labels": ["label1", "label2"],
      "week": 1
    }
  ],
  "impactMetrics": {
    "cycleTimeReduction": "↓ X%",
    "researchHoursSaved": "Xhrs",
    "stackConfidence": "X%"
  }
}

IMPORTANT RULES:
1. The architectureMermaid field MUST be valid Mermaid.js flowchart syntax starting with 'graph TD'
2. Use real emoji in arch icons
3. deepSearchResults should reference REAL papers/repos from the RAG context provided
4. githubIssues should have 4 per week (16 total) - actionable, specific tasks
5. webIntel should list 4 packages from the recommended tech stack
6. sprints must have exactly 4 items (W1-W4)
7. The Mermaid diagram must include ALL main architecture components with arrows showing data flow
8. Add style directives to highlight the AI/ML component: style X fill:#e11d48,color:#fff`;

  const userPrompt = `PROJECT IDEA: ${query}

${ragContext ? `REAL RESEARCH CONTEXT (from live RAG pipeline):
${ragContext}

Use the above research to populate deepSearchResults with REAL paper titles, GitHub repos, and URLs found above.` : 'Note: Generate plausible research citations based on the topic.'}

Generate the complete project blueprint JSON now. Make the architecture Mermaid diagram detailed and specific to this project.`;

  return { systemPrompt, userPrompt };
}

/**
 * Build a README template from blueprint data
 */
function buildReadmeContent(blueprint, repoName) {
  const techList = [
    ...(blueprint.techStack?.frontend || []),
    ...(blueprint.techStack?.backend || []),
    ...(blueprint.techStack?.database || []),
    ...(blueprint.techStack?.aiMl || [])
  ].join(' • ');

  return `# ${blueprint.title}

> ${blueprint.tagline}

## 🎯 Problem Statement

${blueprint.problemStatement}

## 🚀 Tech Stack

${techList}

## 🏗️ Architecture

\`\`\`mermaid
${blueprint.architectureMermaid}
\`\`\`

## 📅 Sprint Plan

${(blueprint.sprints || []).map(s => `### ${s.week}: ${s.title}\n${s.desc}`).join('\n\n')}

## 🔧 Setup

\`\`\`bash
git clone https://github.com/username/${repoName}.git
cd ${repoName}
cp .env.example .env
# Add your API keys to .env
npm install
npm run dev
\`\`\`

## 🌐 Environment Variables

See \`.env.example\` for required variables.

## 📄 License

MIT License — Built with [iNSIGHTS Layer 2](https://github.com/Vinit-vibhandik22/insights-layer2)

---
*Generated by iNSIGHTS Layer 2 AI Copilot*
`;
}

module.exports = { buildBlueprintPrompt, buildReadmeContent };
